version: '3'
services:
  app:
    image: tatsuki1107/recsys
    volumes:
      - ./:/app
    ports:
      - 8888:8888
    tty: true
    platform: linux/amd64
    command: poetry run jupyter lab --allow-root --ip=0.0.0.0 --LabApp.token=""
    env_file:
      - .env

  fast-api:
    container_name: fast-api
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
    tty: true
    env_file:
      - ./api/.env
